"use client";

import React from "react";
import Link from "@/components/AppLink";
import { EyeOff, Ban, HandHeart, ScanSearch, PackageCheck, Undo2, Flag } from "lucide-react";
import { DoneeSectionHeading, DONEE_CARD, DONEE_HEADING_GAP, DONEE_PILL_BUTTON, DONEE_SECTION } from "./DoneeSectionHeading";

/**
 * Each tip describes a flow the platform actually has:
 * - address: delivery/pickup details are requested inside an offer's handover,
 *   i.e. only after the donee has accepted that offer;
 * - codes: the handover code is generated by the donor and entered by the
 *   donee, so a donee never has to give a code to anyone;
 * - decline: the donee reviews every offer and can accept or decline it;
 * - receipt: the donee confirms quantity and condition at handover;
 * - requests can't be edited once submitted (drafts only), but the donee can
 *   withdraw one at any stage short of completion.
 */
const TIPS = [
  {
    icon: EyeOff,
    title: "Your address stays private",
    text: "Your exact address is never shown publicly. Share pickup details only after you accept an offer.",
  },
  {
    icon: Ban,
    title: "Never pay or share bank details",
    text: "CauseKind is free. No donor or CauseKind team member will ever ask you for money or bank details. The only code at a handover is the one the donor gives you.",
  },
  {
    icon: HandHeart,
    title: "Accept only what you need",
    text: "If an offered item doesn't match your need, it's okay to decline. Someone else may need it more.",
  },
  {
    icon: ScanSearch,
    title: "Check the item at handover",
    text: "Make sure it matches what was offered before you mark it as received.",
  },
  {
    icon: PackageCheck,
    title: "Confirm once you receive",
    text: "Marking items received keeps your request up to date and lets the donor know it reached you.",
  },
  {
    icon: Undo2,
    title: "Withdraw what you no longer need",
    text: "If your need changes or has already been met, withdraw your request so donors can help someone else.",
  },
] as const;

/**
 * The only report flow is per offer (`/offers/[id]/issues`), which needs an
 * offer to report against; from the landing page the contact page is the
 * general way to reach the team.
 */
const REPORT_HREF = "/contact";

/** Donee landing only: safety tips for collecting an item. */
export function HandoverTipsSection() {
  return (
    <section
      id="handover-tips"
      aria-labelledby="handover-tips-heading"
      data-ck-role-theme="donee"
      className={DONEE_SECTION}
    >
      <div className="mx-auto max-w-6xl px-5 sm:px-8">
        <DoneeSectionHeading
          id="handover-tips-heading"
          eyebrow="Stay safe"
          title="Receiving safely on CauseKind."
          lede="A few simple habits that keep every handover safe and smooth."
        />

        <ul className={`${DONEE_HEADING_GAP} grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 lg:gap-5`}>
          {TIPS.map((tip) => {
            const Icon = tip.icon;
            return (
              <li key={tip.title} className={`${DONEE_CARD} flex items-start gap-4 p-5`}>
                <span className="w-10 h-10 shrink-0 rounded-xl bg-[var(--ck-role-soft)] text-[var(--ck-role-accent)] flex items-center justify-center">
                  <Icon className="w-5 h-5" aria-hidden="true" />
                </span>
                <div className="min-w-0">
                  <h3 className="text-sm sm:text-base font-bold text-stone-900 dark:text-stone-100">{tip.title}</h3>
                  <p className="mt-1 text-sm text-stone-600 dark:text-stone-400 leading-relaxed">{tip.text}</p>
                </div>
              </li>
            );
          })}
        </ul>

        <div className="mt-6 sm:mt-8 rounded-2xl bg-[var(--ck-role-soft)] px-5 py-4 sm:px-6 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <p className="text-sm font-semibold text-[var(--ck-role-on-soft)]">
            Something not right with a handover? We&apos;re here to help.
          </p>
          <Link href={REPORT_HREF} className={`${DONEE_PILL_BUTTON} self-start sm:self-auto`}>
            <Flag className="w-4 h-4" aria-hidden="true" />
            Report a problem
          </Link>
        </div>
      </div>
    </section>
  );
}
